### ISSUE TITLE
Creating a Script for HOST Chains:

### ISSUE THREAD

**Issue by Eliminater74** [dragon-tc-tmp/DragonTC#2]
I really like your work alot, and wonder if you ever thought about creating a build script that allows
you to build for HOST, and install as host.. Kinda like a package for your destro?

Like I am on Arch Linux and would love to replace the current Clang/LLVM with this one.
Not sure on how to do such.. but would really like it.

**Comment by mydongistiny** [comment]
I just build LLVM for Arch using this PKGBUILD: https://github.com/arch-llvm/llvm-svn

**Comment by Eliminater74** [comment]
Thanks im going to try this out...
